src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    #[Assert\NotBlank(message: 'Please enter a title.')]
    #[Assert\Length(max: 64, maxMessage: 'The title cannot be longer than {{ limit }} characters.')]
    private ?string $title = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Please enter a minimum number of players.')]
    #[Assert\Positive(message: 'The minimum number of players must be greater than 0.')]
    private ?int $min_players = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Please enter a maximum number of players.')]
    #[Assert\Positive(message: 'The maximum number of players must be greater than 0.')]
    private ?int $max_players = null;

    #[ORM\OneToOne(mappedBy: 'game', cascade: ['persist', 'remove'])]
    private ?Contest $contest = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMinPlayers(): ?int
    {
        return $this->min_players;
    }

    public function setMinPlayers(int $min_players): self
    {
        $this->min_players = $min_players;

        return $this;
    }

    public function getMaxPlayers(): ?int
    {
        return $this->max_players;
    }

    public function setMaxPlayers(int $max_players): self
    {
        $this->max_players = $max_players;

        return $this;
    }

    public function getContest(): ?Contest
    {
        return $this->contest;
    }

    public function setContest(Contest $contest): self
    {
        // set the owning side of the relation if necessary
        if ($contest->getGame() !== $this) {
            $contest->setGame($this);
        }

        $this->contest = $contest;

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('min_players', IntegerType::class)
            ->add('max_players', IntegerType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Repository\ContestRepository;
use App\Repository\GameRepository;
use App\Repository\PlayerContestRepository;
use App\Repository\PlayerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GameController extends AbstractController
{
    #[Route('/game', name: 'app_game', methods: ['GET'])]
    public function index(GameRepository $gameRepository, PlayerRepository $playerRepository, ContestRepository $contestRepository, PlayerContestRepository $playerContestRepository): Response
    {
        $games = $gameRepository->findAll();
        $players = $playerRepository->findAll();
        $contests = $contestRepository->findAll();
        $playerContests = $playerContestRepository->findAll();
        return $this->render('game/index.html.twig', [
            'games' => $games,
            'players' => $players,
            'contests' => $contests,
            'playerContests' => $playerContests,
        ]);
    }
}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	<h1 class="pt-5 pb-3">Welcome to My ScoreBoard</h1>
    <h3 class="pb-3">On this page you will find the list of games, players and contests</h3>
    <hr>
	<table class="table mb-5">
        <caption class="text-info">List of games</caption>
		<thead>
			<th>Id</th>
			<th>Title</th>
			<th>Min. Players</th>
			<th>Max. Players</th>
		</thead>
		<tbody>
			{% for game in games %}
				<tr>
					<td>{{ game.id }}</td>
					<td>{{ game.title }}</td>
					<td>{{ game.minPlayers }}</td>
					<td>{{ game.maxPlayers }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
    <hr>

    <table class="table mb-5">
        <caption class="text-info">List of players</caption>
		<thead>
			<th>Id</th>
			<th>E-mail</th>
			<th>Nickname</th>
		</thead>
		<tbody>
			{% for player in players %}
				<tr>
					<td>{{ player.id }}</td>
					<td>{{ player.email }}</td>
					<td>{{ player.nickname }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
    <hr>

    <table class="table mb-5">
        <caption class="text-info">List of contests</caption>
		<thead>
			<th>Game</th>
            <th>Start date</th>
			<th>Number of registred players</th>
            <th>Winner nickname</th>
		</thead>
		<tbody>
			{% for contest in contests %}
				<tr>
					<td>{{ contest.game.title }}</td>
                    <td>{{ contest.startdate|date }}</td>
                    {# <td>{{ contest.players|length }}</td> #}
                    {# <td>{{ contest.nickname }}</td> #}
				</tr>
			{% endfor %}
		</tbody>
	</table>
    <hr>
{% endblock %}